version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chechorios2008
      - MONGO_INITDB_ROOT_PASSWORD=ZTOxIVKaos3w9n9T
    volumes:
      - ./mongo_data:/data/db    